#include <Arduino.h>

String local_json = "{\"SSID\":\"\","
                    "\"PASS\":\"\","
                    "\"MQTT_SERVER\":\"192.168.1.139\","
                    "\"HARDWARE_CONFIGURATION\":"
                    "	{\"SENSOR\":\"greenhouse/sensor\","
                    "	\"GPIO_CONTROLLERS\":["
                    "		{\"ADDRES\":\"100\","
                    "		\"GPIOS\":["
                    "			{\"TYPE\":\"OUT\","
                    "			\"TOPIC\":\"greenhouse/output/light\"},"
                    "			{\"TYPE\":\"OUT\","
                    "			\"TOPIC\":\"greenhouse/output/fan\"},"
                    "			{\"TYPE\":\"OUT\","
                    "			\"TOPIC\":\"greenhouse/output/pump\"},"
                    "			{\"TYPE\":\"IN\","
                    "			\"TOPIC\":\"greenhouse/floodsensor1\"}"
                    "		]},"
                    "		{\"ADDRES\":\"010\","
                    "		\"GPIOS\":["
                    "			{\"TYPE\":\"OUT\","
                    "			\"TOPIC\":\"greenhouse/pump\"},"
                    "			{\"TYPE\":\"IN\","
                    "			\"TOPIC\":\"greenhouse/floodsensor\"}"
                    "		]}"
                    "	],"
                    "   \"ANALOG_CONTROLLERS\":["
                    "       {\"ADDRES\":\"001\","
                    "       \"INPUTS\":["
                    "           {\"TOPIC\":\"greenhouse/input/moisture\"}"
                    "       ]}"
                    "   ]}"
                    "}9965d3c1";