#include <Arduino.h>

String local_json = "{\"SSID\":\"UPCD2A94D7\","
"\"PASS\":\"nG74stttPuzz\","
"\"MQTT_SERVER\":\"192.168.0.17\","
"\"HARDWARE_CONFIGURATION\":"
"	{\"SENSOR\":\"greenhouse/sensor\","
"	\"GPIO_CONTROLLERS\":["
"		{\"ADDRES\":\"100\","
"		\"GPIOS\":["
"			{\"TYPE\":\"OUT\","
"			\"TOPIC\":\"greenhouse/output/light\"},"
"			{\"TYPE\":\"OUT\","
"			\"TOPIC\":\"greenhouse/output/fan\"},"
"			{\"TYPE\":\"OUT\","
"			\"TOPIC\":\"greenhouse/output/pump\"},"
"			{\"TYPE\":\"IN\","
"			\"TOPIC\":\"greenhouse/floodsensor1\"}"
"		]},"
"		{\"ADDRES\":\"010\","
"		\"GPIOS\":["
"			{\"TYPE\":\"OUT\","
"			\"TOPIC\":\"greenhouse/pump\"},"
"			{\"TYPE\":\"IN\","
"			\"TOPIC\":\"greenhouse/floodsensor\"}"
"		]}"
"	]}"
"}9965d3c1";